### ISSUE TITLE
brand icons missing

### ISSUE THREAD

**Issue by bescheid** [ProfessionalWiki/FontAwesome#4]
I tried `{{#fab:wikipedia-w}} `or `{{#fab:google}}` but they did not show up in my present version (1.0). (https://www.univie.ac.at/rel_jap/an/Spezial:Version)

Other icons such as `{{#fas:Times}}` do work.

Files for fonts (extenstions/FontAwesome/.../webfonts/fa-brands-400-eot etc.) seem to be present though.

See: https://www.univie.ac.at/rel_jap/an/Metalog:Sandkiste

Ref: https://www.mediawiki.org/wiki/Topic:Vqk4miw736ggtjwn

**Comment by kghbln** [comment]
Thanks for reporting.

**Comment by s7eph4n** [comment]
The problem is in your MediaWiki:Vector.css:

![image](https://user-images.githubusercontent.com/2829850/88153077-3851a900-cc05-11ea-8dcb-ef8a53a88047.png)

**Comment by bescheid** [comment]
many thx and sorry for the trouble!

**Comment by kghbln** [comment]
@s7eph4n Thanks for having a quick look and clarifying!

@bescheid It will be great to get cross-references from discussions to the bug report and vice versa. I assume that this [discussion thread](https://www.mediawiki.org/wiki/Topic:Vqk4miw736ggtjwn) is from you. There is no reference to this bug over there and in your bug report here is no reference to the discussion. This potentially creates double work for people wanting to help and missing half of what is going on or if there is a solution already. I believe this unfair. If you did not create this on MediaWiki.org please disregard my grump.

**Comment by bescheid** [comment]
@kghbln Sorry, muss mich erst an eure ganzen Tools gewöhnen, gelobe aber Besserung... :)
